### ISSUE TITLE
Called Process Error

### ISSUE THREAD

**Issue by ptzool** [stackanetes/stackanetes#137]
Hi,

I tried to install stackanetes to a coreos cluster but I got the following error message. What did I do wrong?

```
Traceback (most recent call last):
 File "/usr/bin/kpm", line 6, in <module>
   cli()
 File "/usr/lib/python2.7/site-packages/kpm/command.py", line 63, in cli
   args.func(args)
 File "/usr/lib/python2.7/site-packages/kpm/commands/command_base.py", line 16, in call
   self(options)()
 File "/usr/lib/python2.7/site-packages/kpm/commands/command_base.py", line 19, in __call__
   self._call()
 File "/usr/lib/python2.7/site-packages/kpm/commands/deploy.py", line 60, in _call
   fmt=self.output)
 File "/usr/lib/python2.7/site-packages/kpm/deploy.py", line 89, in deploy
   return _process(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/kpm/deploy.py", line 62, in _process
   status = getattr(kubresource, action)(force=force, dry=dry)
 File "/usr/lib/python2.7/site-packages/kpm/kubernetes.py", line 113, in create
   self._call(cmd, dry=dry)
 File "/usr/lib/python2.7/site-packages/kpm/kubernetes.py", line 177, in _call
   return subprocess.check_output(command, stderr=subprocess.STDOUT)
 File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
   raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['kubectl', 'create', '-f', '/tmp/tmpddIQc2', '--namespace', u'openstack']' returned non-zero exit status 1

```

**Comment by Quentin-M** [comment]
Hi there,

I believe that the packages on the public repository were out of date. I just updated them based on _master_. Could you please try again?

**Comment by ptzool** [comment]
Hi,

Same error. :(

**Comment by Quentin-M** [comment]
The error means that _kubectl_ failed to create the resource. However, the output isn't clear and it isn't straight-forward to determine which manifest exactly isn't accepted and for which reason. It is a feedback I've given few weeks ago but it apparently never made it upstream. Ideally, _kpm_ would show the guilty file and the reason. I just created an issue () and I'll see what I can do about it tomorrow. Until then, we have to guess which package failed, then try to manually create its manifests (from /tmp) using the CLI.

Does it happen at the very beginning or some resources actually got created?
Could you please share the result of `kubectl version`?

**Comment by ptzool** [comment]
Hi,

I reinstalled the cluster, and it works. I think I made a mistake.. Sorry.

**Comment by Quentin-M** [comment]
I'm glad it worked out, have a nice day!
