### ISSUE TITLE
path hacks on OSX

### ISSUE THREAD

**Issue by polvi** [stackanetes/stackanetes#15]
When installed on OSX, the services get installed to locations such as: 

```
/System/Library/Frameworks/Python.framework/Versions/2.7/share/kolla-k8s/config
```

This results in needed hacks like:

```
ln -s /System/Library/Frameworks/Python.framework/Versions/2.7/share/kolla-k8s/config /usr/share/kolla-k8s/config
```

**Comment by v1k0d3n** [comment]
I'm getting the following error...

```
2016-05-10 15:52:28.027 65706 DEBUG cliff.commandmanager [-] found command 'run' load_commands /Library/Python/2.7/site-packages/cliff/commandmanager.py:47
2016-05-10 15:52:28.027 65706 DEBUG cliff.commandmanager [-] found command 'kill' load_commands /Library/Python/2.7/site-packages/cliff/commandmanager.py:47
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s [-] The service directory "/Library/Python/2.7/site-packages/services" was not found
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s Traceback (most recent call last):
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s   File "/Library/Python/2.7/site-packages/cliff/app.py", line 346, in run_subcommand
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s     result = cmd.run(parsed_args)
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s   File "/Library/Python/2.7/site-packages/cliff/command.py", line 55, in run
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s     self.take_action(parsed_args)
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s   File "/Library/Python/2.7/site-packages/kolla_k8s/cli/service.py", line 34, in take_action
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s     CONF.service_dir)
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s   File "/Library/Python/2.7/site-packages/kolla_k8s/service.py", line 278, in run_service
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s     _build_runner(service, service_dir, variables=variables)
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s   File "/Library/Python/2.7/site-packages/kolla_k8s/service.py", line 215, in _build_runner
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s     service_dir)
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s   File "/Library/Python/2.7/site-packages/kolla_k8s/service_definition.py", line 37, in find_service_file
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s     entity='service directory')
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s KollaNotFoundException: The service directory "/Library/Python/2.7/site-packages/services" was not found
2016-05-10 15:52:28.130 65706 ERROR kolla-k8s
2016-05-10 15:52:28.132 65706 CRITICAL kolla_k8s [-] KollaNotFoundException: The service directory "/Library/Python/2.7/site-packages/services" was not found
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s Traceback (most recent call last):
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s   File "/usr/local/bin/kolla-k8s", line 10, in <module>
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s     sys.exit(main())
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s   File "/Library/Python/2.7/site-packages/kolla_k8s/cmd/shell.py", line 161, in main
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s     return KollaMesosShell().run(command_args)
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s   File "/Library/Python/2.7/site-packages/cliff/app.py", line 226, in run
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s     result = self.run_subcommand(remainder)
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s   File "/Library/Python/2.7/site-packages/cliff/app.py", line 346, in run_subcommand
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s     result = cmd.run(parsed_args)
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s   File "/Library/Python/2.7/site-packages/cliff/command.py", line 55, in run
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s     self.take_action(parsed_args)
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s   File "/Library/Python/2.7/site-packages/kolla_k8s/cli/service.py", line 34, in take_action
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s     CONF.service_dir)
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s   File "/Library/Python/2.7/site-packages/kolla_k8s/service.py", line 278, in run_service
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s     _build_runner(service, service_dir, variables=variables)
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s   File "/Library/Python/2.7/site-packages/kolla_k8s/service.py", line 215, in _build_runner
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s     service_dir)
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s   File "/Library/Python/2.7/site-packages/kolla_k8s/service_definition.py", line 37, in find_service_file
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s     entity='service directory')
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s KollaNotFoundException: The service directory "/Library/Python/2.7/site-packages/services" was not found
2016-05-10 15:52:28.132 65706 ERROR kolla_k8s
```

**Comment by v1k0d3n** [comment]
@polvi what are your thoughts about handing the deployment of stackanetes with a deployment container? this way all the dependancies will be included, `kubectl` config could be fetched, and deployment tasks could be parameters used by the container. thoughts?

**Comment by v1k0d3n** [comment]
scratch that! i see PR #20 :)

**Comment by alekssaul** [comment]
@polvi @v1k0d3n : There has been some work on #23 to facilitate Openstack install via deployment container. Deployment container seem to work well in few runs we've tested. Deployment container should have all the kolla-k8s requirements in it. Users on any platform with kubectl should be able to just use deployer container to bootstrap openstack on k8s. 

Do you think #23 satisfies this issue for now?

**Comment by philips** [comment]
Yes, lets move as much on cluster as possible. Closing this out.

**Comment by philips** [comment]
Reopening since #23 isn't merged into master yet.

**Comment by DTadrzak** [comment]
#23 has been Merged, so i close it
